- backend/fms_core/migrations/0016_v3_1_0.py
- backend/fms_core/migrations/0017_v3_1_0.py
* I have read about other ways of optimizing the django orm queries, either by using bulk_update/bulk_create (which bypass the save()/presave/postsave methods in the models btw), or using iterator() instead of caching the whole queryset into the memory, but I did not have much proof of the efficiency when running our migration.
* The best I could do is to regroup all the versions modifications into a single operation rather than many. Going through the 80K Sample objects in Version were the slower steps, and we do not modify Sample Versions during the migration when making modifications to Sample objects anyways, so the order of operations does not really matter in our case. 
On my local machine, I was able to reduce the migration time from 4min30 to 2mins30, which is still a significant …
> Migration optimization

- frontend/src/components/samples/SampleEditContent.js
Tested it with templates and in the backend where the tissue source is optional.
It appears that it only shows as required for DNA/RNA in the front-end form.
> Tissue source optional

- backend/fms/settings.py
Closes https://206.12.92.46/issues/368
Uses $FREEZEMAN_SECRET_KEY when availabe.
@UlysseFG this will require you to update the dev/prod env to add a secret key in the environment variables.
> Use FREEZEMAN_SECRET_KEY when available

- backend/fms_core/management/commands/_delete_individual.py
- backend/fms_core/management/commands/_update_field_value.py
- backend/fms_core/management/commands/curation.py
- backend/fms_core/migrations/0019_v3_1_2.py
- backend/fms_core/models/sample.py
- backend/fms_core/models/tracked_model.py
This is a curation script that deals with individual deletions. It confirms the individuals are not linked as parents to another individual and they do not have samples linked to them. This PR also move the actual deletion outside the Revision block to make sure a last version of the deleted item is saved.
> New curation script to delete individuals.

- frontend/src/utils/renderSampleDiff.js
This is mainly to accomodate the use of the 'Experimental group' field which is a JSON field. It would not render properly in the Sample Detail page, in the Versions box. 
PS: @UlysseFG  I could open another PR to have it merged to QC too if you want..
> Handle JSON fields in Sample Versions Diff

- backend/fms_core/router.py
- backend/fms_core/serializers.py
- backend/fms_core/viewsets.py
- frontend/src/components/users/UsersDetailContent.js
- frontend/src/modules/samples/reducers.js
- frontend/src/modules/users/actions.js
- frontend/src/modules/users/reducers.js
- frontend/src/utils/api.js
- frontend/src/utils/preprocessRevisions.js
More efficient way of loading versions in a User details page. 
On page loading, it loads the Revision objects. And it only loads the corresponding Version objects when you click on a Revision (+) button. 
@romgrk not a big deal, but I'm not sure about having those Versions still stored in the Redux store (under Users/itemsByID/Versions)..
> Revision endpoint for users

- backend/fms/settings.py
Change the name of the secret key env variable to match the format used for other env variables in the app.
> rename secret key variable

- backend/fms_core/resources/_generic.py
The template fails when there is too many errors because the warnings are not set. Setting the warning to an empty list in that case.
> Set empty warning when too many errors.

- backend/fms_core/viewsets.py
- frontend/src/components/PaginatedTable.js
- frontend/src/components/filters/descriptions.js
- frontend/src/components/filters/getFilterProps.js
- frontend/src/utils/serializeFilterParams.js
Description: This allows the user to lookup samples by containers recursively. Let's say rack 1 (barcode: rack1) contains tube A (sample A), tube B (sample B), tube C (sample C). When looking up in the Sample list page by applying filter container barcode 'rack1', you will get a list of samples with sample A, sample B, sample C. Previously you would not get any sample in the list, because rack1 does not contain any sample directly.
Name of recursive option and variable are open for discussion :)
> Recursive container search

- frontend/src/components/TemplateFlow.js
In the case where there are errors found while submitting the template, but those are errors independent from the template submission, the page would crash and not render.
This fix would at least not make the page crash and display an error such as
> Fix TemplateFlow with errors but no base error

- backend/fms_core/models/library.py
Hotfix for QC branch
Changed:
`return Decimal(SSDNA_MW if self.strandedness is SINGLE_STRANDED else DSDNA_MW)`
to:
`return Decimal(SSDNA_MW if self.strandedness == SINGLE_STRANDED else DSDNA_MW)`
The `is` comparison fails if self.strandedness is not the string constant object SSDNA_MW - if it's a copy of the string then the test fails and the function always returns DSDNA_MW, leading to an error when we calculate the concentration in nM.
> Fix molecular_weight_approx for single stranded dna

- backend/fms_core/template_importer/importers/sample_submission.py
- backend/fms_core/utils.py
Fixes redmine issue: [Feature #1185](https://206.12.92.46/issues/1185)
Container kind strings are stored in lower case in the db. In the sample submission form the drop down uses "Tube" as the type. Container kind strings need to be converted to lowercase by the importer.
> Fix container type casing error for "Tube" type

- backend/fms_core/template_importer/row_handlers/sample_submission/sample.py
If an imported sample name has an case-insensitive match with an existing sample then check to see if it's an exact match and output the appropriate warning.
> Fix sample name warning

- backend/fms_core/viewsets/imported_file.py
- frontend/src/utils/api.js
Fixes redmine ticket https://206.12.92.46/issues/1199
The original problem seems to be caused by the Content-Type being set to None for the downloaded file.
We are using the `mimetypes` python module to determine a content type for the template file. By default, mimetypes gets the mime types from the system on which it is running. On our dev machines, it is getting it from MacOS or Linux. I guess that on the server there is no mapping for xlsx files, and the `mimetypes.guess_types()` call is returning None.
My simple fix is to default to `application/octet-stream` if guess_types returns None.
I am also going to see how complicated it is to configure the mimetype for xlsx files, to return the proper type without defaulting to system types. …
> Fix corrupt imported template downloads RM#1199

- backend/fms_core/viewsets/_constants.py
- frontend/src/components/filters/descriptions.js
- frontend/src/components/filters/getFilterProps.js
- frontend/src/constants.js
- frontend/src/modules/containers/reducers.js
- frontend/src/modules/experimentRuns/reducers.js
- frontend/src/modules/indices/reducers.js
- frontend/src/modules/individuals/reducers.js
- frontend/src/modules/libraries/reducers.js
- frontend/src/modules/processMeasurements/reducers.js
- frontend/src/modules/projects/reducers.js
- frontend/src/modules/samples/reducers.js
- frontend/src/modules/users/reducers.js
- frontend/src/utils/serializeFilterParams.js
This is a quick fix that solves the immediate problem of a bad filter value causing an infinite loop of requests from a PaginatedTable, but which just makes the whole system a bit more complicated and difficult to understand. This could be merged if a better fix is going to take a long time to implement.
> Quick fix for infinite loop of item requests

- frontend/src/components/projects/ProjectsAssociatedSamples.js
Rendering a pool in the list of samples displayed in the project details page would cause the app to crash, because the `sample_kind` property of a pool sample is undefined.
This fix just adds a check for the `sample_kind` property before rendering the Tag for the sample kind.
> Fix project details crash rendering pool samples

- backend/fms_core/viewsets/project.py
- frontend/src/components/samples/details/SampleDetailsContent.js
Issues were there was many projects for pool in related projects tab and the index would be loading for pools in the sample detail.
> distinct() on project queryset. Hide index for pools in sample details.

- frontend/src/components/templateFlow/TemplatePreview.js
Removed hash url's from the TemplatePreview Tabs component.
There were two problems:
1. We are using integer values as TabPane keys, but the Tabs component doesn't render the first tab if the active key is set to zero.
2. The hash remains in the url if the user navigates back to the upload "page" (by clicking the Previous button), which is weird. The best fix for that would be to use separate routes for the different states of the TemplateFlow component (UPLOAD/REVIEW/CONFIRM), but that would be a major change.
> Removed useHashUrl from TemplatePreview

- frontend/src/components/processMeasurements/ProcessMeasurementsDetailContent.js
- frontend/src/components/samples/details/SampleDetailsContent.js
- frontend/src/components/samples/details/SampleDetailsLineage.js
- frontend/src/hooks/useHashURL.js
The new hash url feature broke lineage graph navigation. When the user clicks a node in the graph we navigate to the clicked sample. The url generated by the graph did not include the `#lineage` key, so the url would navigate the user to the Overview tab of the sample details page, rather than the lineage graph.
Now the sample url will include the `#lineage` key and the user will remain in the lineage graph.
To avoid problems in the future, I made the navigation functions props of SampleDetailsLineage to avoid having hard-coded links in the graph itself.
I also fixed the key for the Pool tab, which was still a number rather than "pool".
I cleaned up some dead code and useless imports I found in the code I touched.
In the urlHash code, I stopped setting the default hash key automatically …
> Fixes lineage graph navigation

- backend/fms_core/tests/test_services/experiment_run_info_test.py
I moved the templates for my experiment_run_info tests and forgot to update the path to the templates folder. This fixes the problem.
> Fixed path to templates folder

- backend/fms_core/viewsets/sample_next_step.py
- frontend/package-lock.json
- frontend/src/components/labwork/LabworkPage.tsx
- frontend/src/components/labwork/overview/LabworkOverviewProtocols.tsx
- frontend/src/modules/labwork/actions.ts
- frontend/src/modules/labwork/services.ts
Display protocols in the labwork overview page in a sensible order - the order in which they normally appear in workflows.
The idea is to look at each protocol and see which protocols it should follow and which it should precede based on where it appears in the workflows.
This gets done once, the first time the labwork is fetched from the backend, after the app is initialized and all the workflow definitions have been loaded.
I also tweaked the labwork-info endpoint in sample_next_step to avoid returning info about steps that are not used in any workflow - I was getting an Infinium protocol that is not used in any workflow and always had zero samples.
> Sort protocols by workflow order

- frontend/src/components/labwork/overview/LabworkOverviewStepGroup.tsx
- frontend/src/modules/labwork/services.ts
Library Preparation steps are grouped by platform (ILLUMINA, DBNSEQ). The "DBNSEQ" group title wasn't being displayed. This PR fixes that. The group title is always displayed, even if there is only a single step in the group.
> Fix step grouping 1564

- frontend/src/components/labwork/overview/LabworkOverview.tsx
- frontend/src/components/labwork/overview/LabworkOverviewProtocols.tsx
- frontend/src/components/labwork/step/LabworkStep.tsx
In the labwork overview page, the page would be dimmed every 30 seconds when the labwork is refreshed. Now the page is only dimmed if the labwork summary hasn't been loaded yet.
I also adding spinning to the Refresh buttons in the labwork and step pages to indicate when the page is being refresh.
> Don't disable labwork on refresh

- frontend/.eslintrc.js
- frontend/.tsconfig
- frontend/package.json
- frontend/src/components/labwork/LabworkPage.tsx
- frontend/src/components/labwork/overview/LabworkOverviewProtocols.tsx
- frontend/src/components/labwork/step/LabworkStep.tsx
- frontend/src/components/labwork/step/LabworkStepRoute.tsx
- frontend/src/components/projects/ProjectsDetailedContent.tsx
- frontend/src/components/projects/ProjectsPage.js
- frontend/src/components/shared/WithItemComponent.tsx
- frontend/src/components/shared/WorkflowSamplesTable/MergeColumnsAndFilters.ts
- frontend/src/components/shared/WorkflowSamplesTable/SampleTableColumns.tsx
- frontend/src/components/shared/WorkflowSamplesTable/WorkflowSamplesTable.tsx
- frontend/src/components/shared/WorkflowSamplesTable/serializeFilterParamsTS.ts
- frontend/src/components/studies/StudyDetails.tsx
- frontend/src/components/studies/StudyEditContent.tsx
- frontend/src/models/frontend_models.ts
- frontend/src/models/paged_items.ts
- frontend/src/modules/labwork/actions.ts
- frontend/src/modules/labworkSteps/reducers.ts
The sample KIND column filter needs to be initialized from the sample kinds contained in the redux store - we have to generate a list of options for the Select element. This change adds the ability to define a function to generate the options dynamically.
It also cleans up some excessive rendering in the LabworkStep component by making proper use of `useCallback` and `useMemo`.
Finally, I fixed a bug in the filter serializer for SELECT values.
> Generate filter options dynamically

- frontend/src/components/containers/ContainersListContent.js
- frontend/src/components/experimentRuns/ExperimentRunsListContent.js
- frontend/src/components/indices/IndicesListContent.js
- frontend/src/components/libraries/LibrariesListContent.js
- frontend/src/components/processMeasurements/ProcessMeasurementsListContent.js
- frontend/src/components/projects/ProjectsListContent.js
- frontend/src/components/samples/SamplesListContent.js
- frontend/src/utils/prefillTemplates.js
- frontend/src/utils/templateActions.js
Fixes a react 'unique key' error in  pages that include the actions dropdown and prefilled templates dropdown. This is to reduce noise in the console.
I converted the functions that generate these dropdowns to proper React components so that I could assign a key to the dropdown elements where they are used in page headers.
~~There shouldn't be any change in the existing behaviour of the dropdowns.~~
The template actions and prefilled template menu were tweaked so that menu item buttons span the entire width of the menu (except for ant padding).
> Fix unique key errors in list pages

- frontend/src/components/libraries/LibrariesListContent.js
Replaces withItem functions with WithItemRenderComponent components to fix react state errors.
Also, a small linter fix for unnecessary `break` statements in a switch case.
Removed unused imports.
> Fix withItem errors in LibrariesListContent

- frontend/src/components/App.js
Increase the sidebar width to fit "Reference Genomes". The width is set to 17em, to make the sidebar width relative to the font size. 
Ideally we would set the width to 'auto' but that causes the sidebar width to change whenever the "Definitions" section is expanded or collapsed - it jumps around. :(
> Widen sidebar for Reference Genomes

- frontend/src/components/App.js
- frontend/src/styles/global.css
- frontend/webpack.config.js
https://206.12.92.46/issues/1635
- Add QC or LOCAL next to Freezeman name in the left bar in order to identify the instance.
- Use black-yellow zebra pattern to identify further
LOCAL:
QC:
PROD:
> Feature #1635: Add a way to visually identify QC and DEV instance

- frontend/src/components/PaginatedTable.js
In the processes table, if you set the page size to 50 or 100 then freezeman would go into an infinite loop of requesting process measurements, because it was still asking for only 20 items (the default page size) and never loading 100 pm's.
> QC: fix infinite loop in process measurements table

- frontend/src/modules/studySamples/services.ts
- frontend/src/utils/api.js
Fixes the issue where only the first 100 completed samples are ever retrieved for the project study samples tables.
> QC: Fix missing completed samples in project study

- frontend/src/modules/studySamples/services.ts
- frontend/src/utils/api.js
Fixes the issue with missing completed samples in the project study samples tables - only the first 100 samples were retrieved from the server because no limit was specified and the default limit of 100 was used.
> Fix completed samples 100 limit

- frontend/src/components/PaginatedTable.js
Setting the page size to 100 in the Process Measurements table causes an infinite loop of requests for process measurements.
The problem is that the table wants 100 items, but isn't passing the page size limit to the listTable function, so the listTable function is using the default page size of 20. The table keeps asking for 100 items and 20 items are loaded, producing an infinite loop of listTable requests.
Passing the pageSize expected by the table fixes the problem, for PM's and for any other listTable functions that aren't grabbing the page size out of redux themselves.
> Fix infinite loop of loading PMs

- backend/fms_core/viewsets/sample_next_step.py
- backend/fms_core/viewsets/sample_next_step_by_study.py
- frontend/src/components/shared/WorkflowSamplesTable/ColumnSets.ts
- frontend/src/components/shared/WorkflowSamplesTable/MergeColumnsAndFilters.ts
- frontend/src/components/shared/WorkflowSamplesTable/SampleTableColumns.tsx
- frontend/src/components/studySamples/StudyStepSamplesTable.tsx
The sample-next-step and sample-next-by-study endpoints would return multiple instances of the same pool if the user filters by project name. This PR fixes that. It also disables sorting on the project column, because that also results in multiple instances of the same pool in the endpoint responses.
> Return distinct pools from sample-next-step endpoints

- frontend/src/components/templateFlow/TemplateFlow.js
If the user modifies a template after it has been uploaded then when they try to submit a 'failed to fetch' error is thrown. Catch the error and pop an error notification to explain why submit has failed.
> Modified template submission error alert

- backend/fms_core/serializers.py
- frontend/src/components/referenceGenomes/EditReferenceGenomes.tsx
- frontend/src/components/referenceGenomes/ReferenceGenomeTableColumns.tsx
- frontend/src/components/referenceGenomes/ReferenceGenomesListContent.tsx
- frontend/src/components/taxons/EditTaxon.tsx
- frontend/src/components/taxons/TaxonTableColumns.tsx
- frontend/src/components/taxons/TaxonsListContent.tsx
- frontend/src/models/fms_api_models.ts
- adding authentication for edit Taxons and reference genomes. (checks if logged_user is a superuser to allow them to edit Taxons and reference genomes)
- changing Taxon serializer to append boolean to FMSTaxon, to see if it's ncbi_id can be edited. (checks if there are existing individuals associated to a certain Taxon)
> Edit def. auth + Individuals associated to Taxon

- frontend/src/components/shared/WorkflowSamplesTable/LibraryTableColumns.tsx
The LibraryTableColumns file contained a duplicate PLATFORM_NAME column definition, causing a tsc complication error.
> Remove duplicate PLATFORM_NAME definition

- frontend/src/components/ExportButton.js
I removed the `exportType` prop from `ExportButton` because I didn't think it was used anywhere. I guess the extra space added in the button title was bothering me, "Export ". I didn't realize that ExportDropdown was using the `exportType` prop.
> Fixes 'Export samples' 'Export metadata'

- frontend/src/components/shared/WithItemRenderComponent.tsx
Doh. WithItemRenderComponent was rendering "placeholder" instead of the placeholder element. I got rid of the test for "string" and just return placeholder directly, since react will render the string.
> Fixed "placeholder" bug

- frontend/src/components/DashboardPage.js
Possible fix for broken action template download links in QC when connecting through an ssh tunnel.
We load the template actions when the app launches, but Dashboard was firing off it's own request to load the template actions. It's possible that this causes the strangeness on QC.
The second request for template actions by the dashboard is redundant and has been removed.
"Template actions url's are broken on QC"
https://206.12.92.46/issues/1765
> Remove redundant request for template actions in Dashboard

- frontend/src/components/App.js
- frontend/src/store.ts
Fixes an issue where the sidebar would mysteriously disappear from freezeman.
App.js only renders the sidebar if it finds a user ID in the auth state in redux. If there is no user ID then it skips the sidebar, but still renders the dashboard (which makes no sense - we should fix that someday).
Normally if there is no user ID then there will be no tokens either and users are bounced to the login page.
Somehow, we were ending up with a null user ID but valid tokens in the auth state, so most of the app functioned normally but the sidebar wouldn't render.
I think this was caused by a race condition. When the app starts up it checks any tokens it has (loaded from local storage into redux by the persist framework). If the access token is expired but the refresh token is still valid then it …
> Fix missing sidebar

- frontend/src/utils/api.js
Foiled again by a missing `/` character at the end of an api call in api.js (experimentRuns.get).
> Fixes bug 1915

- frontend/src/components/readsets/ReadsetsListContent.tsx
The ReadsetsListContent table was resetting its paged items state a bit too often (whenever the dataset state would change). This fix just makes sure the paged items state is only wiped if the user is switching to a different dataset.
> Fix paged items issue with readsets

- frontend/src/modules/labworkSteps/actions.ts
* Fixes #756 
* Ensures sample__id__in is actually passed to body and not query param.
> Fix labwork-step-info

- frontend/src/components/placementVisuals/AddPlacementContainer.tsx
- frontend/src/components/placementVisuals/Cell.tsx
- frontend/src/components/placementVisuals/Placement.tsx
- frontend/src/components/placementVisuals/PlacementSamplesTable.tsx
> Placement Tweaks Tweaks

- frontend/src/components/studySamples/StudySamples.tsx
This is to address the worry that the sample did not complete the previous step when removing the sample from the study at a later step. It made it look like the sample were removed before the previous step which is not the case, This is mainly to alleviate that fear.
> In Project study display, make clear removed samples completed their last step.
