backend/fms_core/resources/transfer.py

Some improvements.
Note: for a get_or_create function, for the cases where the attrs in get would differ from the ones for the create, I learned that there is the default= attribute that prevents those fields from being looked up in the get, but are used for the create. ;P

Improve Sample Transfer resource code

---

backend/fms_core/models/sample.py

I realize there was some data validation error making the app crash when creating a sample in the old DjangoAdmin SampleForm interface. Even though this interface will not be used, it still pointed to fixes that had to be done for the Sample model in clean()

Change clean validations in Sample

---

frontend/cypress/integration/all.spec.js

This should be working fine. I am mostly looking for feedback on cypress DOM functions used, and possibly some insights on the code structure of the tests for the near future. Is it usually organized in a similar fashion to components? (i.e. having a file for Containers tests, another for Samples tests, etc.) how are the files split?

Visit single item pages in integrations test

---

backend/fms_core/viewsets.py
frontend/src/components/App.js
frontend/src/components/profile/ProfileContent.js
frontend/src/components/profile/ProfilePage.js
frontend/src/styles/antd-adjustments.scss
frontend/src/styles/global.css

Closes https://206.12.92.46/issues/327
This PR implements a profile page that allows the user to modify some of their details. User permissions not included for the moment.

User password & permissions

---

frontend/src/components/samples/SamplesDetailContent.js
frontend/src/constants.js
frontend/src/utils/renderSampleDiff.js

I dont really like how usersByID has to be passed everywhere, but that's how I can get the username instead of user id...

Change Sample Diff to accomodate user fields

---

backend/fms_core/resources/_generic.py
frontend/src/components/TemplateFlow.js

WIP. Currently only returning one error by line for some reason need to be investigated.

Interrupt ressource processing after too many errors were found.

---

frontend/src/constants.js
frontend/src/styles/global.css
frontend/src/utils/dateToString.js
frontend/src/utils/humanReadableTime.js
frontend/src/utils/renderSampleDiff.js

Closes https://206.12.92.46/issues/373
Closes https://206.12.92.46/issues/365
Changes date rendering in the sample history timeline.

Date format

---

frontend/src/index.js
frontend/src/reducers.js

Closes https://206.12.92.46/issues/367#change-1326
Test with:
```js
// directly in browser console
s = JSON.parse(localStorage['persist:auth'])
ts = JSON.parse(s.tokens)
ts.access = 'abcdef'
ts.refresh = 'abcdef'
s.tokens = JSON.stringify(ts)
localStorage['persist:auth'] = JSON.stringify(s)
```

Logout notifications

---

frontend/src/components/users/UsersDetailContent.js
frontend/src/modules/users/actions.js
frontend/src/modules/users/reducers.js
frontend/src/utils/api.js
frontend/src/utils/preprocessVersions.js

Closes https://206.12.92.46/issues/366
Implements paged loading for revisions in user details page.

Add paged loading for user history

---

frontend/src/modules/samples/reducers.js
frontend/src/modules/users/reducers.js
frontend/src/utils/preprocessVersions.js

This PR https://github.com/c3g/freezeman/pull/36 had unwanted side-effects on the Sample details versions. 
This is a quick fix to remedy it.

Fix preprocess versions utils for Sample and User

---

backend/fms_core/migrations/0020_v3_2_0.py

Duplication of https://github.com/c3g/freezeman/pull/68 for QC this time instead of master.

Add missing Sample individual migration (QC)

---

backend/fms_core/migrations/0020_v3_2_0.py

Let me know if this is what you meant, will merge it to master, and will make a similar PR to QC

Add missing Sample individual migration to 3.2.0 (Master)

---

backend/fms_core/resources/sample_update.py

When we compute the new volume with a delta volume we need to convert the resulting volume to a Decimal of 3 positions.

applying conversion to decimal to volume computation using delta volume.

---

frontend/src/components/samples/details/SampleDetailsProcessMeasurements.js

This column wouldnt display due to the condition id && ... 
This condition was simply removed

Fix display of Process link in Sample detail

---

backend/fms/settings.py

Renaming the secret key env variable to match the pattern used across the app.

Rename secret key env variable

---

backend/fms_core/resources/_generic.py

Define warnings on row_results when there is too many errors.

Define warnings when there is too many errors.

---

frontend/webpack.config.js

Server was not finding the .env file required to load environment variables to the frontend. The fix sets the relative path to the file.

small fix to help the servers locate the .env file

---

backend/fms_core/migrations/0021_v3_3_0.py
backend/fms_core/models/__init__.py
backend/fms_core/models/experiment_run.py
backend/fms_core/models/experiment_type.py
backend/fms_core/tests/test_models/experiment_run_test.py
backend/fms_core/tests/test_models/experiment_type_test.py

TODO: add unit tests, and possibly fill the db with a first ExperimentType for Illuminium

ExperimentType and ExperimentRun

---

frontend/cypress/integration/all.spec.js
frontend/cypress/integration/pagination.spec.js
frontend/src/components/PaginatedTable.js
frontend/src/modules/containers/actions.js
frontend/src/modules/containers/reducers.js
frontend/src/modules/individuals/actions.js
frontend/src/modules/individuals/reducers.js
frontend/src/modules/pagination.js
frontend/src/modules/samples/actions.js
frontend/src/modules/samples/reducers.js
frontend/src/modules/users/actions.js
frontend/src/modules/users/reducers.js
frontend/src/reducers.js

Added a new module to deal with the pageSize state. Modified the action.js of container, individuals, samples and containers to take in account the pageSize state. Finally, added the new reducer to the store.

Implemented dynamic page size for pagination

---

DEPLOYMENT.md
backend/README.md
frontend/src/components/experimentRuns/ExperimentRunsListContent.js
frontend/src/components/samples/details/SampleDetailsProcessMeasurements.js

Removed Experiment from start date to prevent it wrapping and move ul to header in sample detail process listing.

Minor frontend changes

---

backend/fms_core/tests/test_models/project_test.py

Just a quick fix that was supposed to be implemented in the last PR.

Fixed backend tests

---

frontend/src/components/filters/descriptions.js
frontend/src/components/samples/SamplesListContent.js

Only question is if the column's position is correct (between concentration and depleted)

Added creation date column

---

frontend/src/components/processMeasurements/ProcessMeasurementsListContent.js
frontend/src/constants.js

1. https://206.12.92.46/issues/912?issue_count=54&issue_position=6&next_issue_id=910&prev_issue_id=913
2. https://206.12.92.46/issues/913

Backlog protocol list font fix

---

backend/fms_core/filters.py
backend/fms_core/viewsets/container.py
backend/fms_core/viewsets/full_sample.py
backend/fms_core/viewsets/individual.py
backend/fms_core/viewsets/sample.py
frontend/src/components/filters/descriptions.js
frontend/src/utils/serializeFilterParams.js

Please leave the comments in this new PR.

Implemented batch filtering for samples, containers and individuals

---

backend/fms_core/services/experiment_run.py
backend/fms_core/services/process_measurement.py
backend/fms_core/services/property_value.py
backend/fms_core/template_importer/row_handlers/sample_qc/sample.py

For experiment run and sample qc

Fixed and modified mandatory property validation 

---

backend/fms_core/filters.py
frontend/src/components/filters/descriptions.js

In addition, I made the filter generic since many attributes are using it

Implemented batch filter for project

---

backend/fms_core/services/sample_lineage.py
backend/fms_core/viewsets/sample_lineage.py
frontend/src/components/samples/details/SampleDetailsLineage.js

fix centering bug in the lineage and a few others.
i only discover bugs when I'm confident about my code :'(

fix centering bug in the lineage

---

backend/fms_core/template_importer/sheet_data.py

Row numbers for imports are off by one (row 8 is displayed as #9).

Fix row number in template import

---

backend/README.md

Restoring this branch to merge again into master.

Postgres db update readme

---

backend/fms_core/filters.py

https://206.12.92.46/issues/984

Fix Search samples by project not consistent

---

backend/fms_core/viewsets/imported_file.py

Hot fix for corrupt imported template download files.

Fixes corrupt imported templates

---

frontend/src/components/samples/details/SampleDetailsProcessMeasurements.js

https://206.12.92.46/issues/1189

Fix Add a simpler way to access templates stored in Freezeman

---

backend/fms_core/template_importer/row_handlers/extraction/extraction.py

Removed unnecessary lower() call on row handler for container kind since it is been taking care of in the importer

Fixed extraction row handler

---

backend/fms_core/serializers.py
backend/fms_core/viewsets/sample_pooled.py
frontend/src/components/samples/details/SampleDetailsPool.js
frontend/src/utils/api.js

Users can export pooled samples from the pooled samples detail page.

Export pooled samples to CSV

---

frontend/src/components/containers/ContainerEditContent.js
frontend/src/components/indices/IndicesValidate.js
frontend/src/components/individuals/IndividualEditContent.js
frontend/src/components/projects/ProjectEditContent.js
frontend/src/components/samples/SampleEditContent.js
frontend/src/components/users/UserEditContent.js

Added a Cancel button to EditContent pages. The button just navigates the user back, equivalent to hitting the browser back button.

Add Cancel button to EditContent pages

---

backend/fms_core/migrations/0034_v3_8_0.py
backend/fms_core/models/study.py
backend/fms_core/router.py
backend/fms_core/serializers.py
backend/fms_core/services/study.py
backend/fms_core/tests/test_models/study_test.py
backend/fms_core/viewsets/__init__.py
backend/fms_core/viewsets/_constants.py
backend/fms_core/viewsets/reference_genome.py
backend/fms_core/viewsets/study.py
backend/fms_core/viewsets/workflow.py

Rebased on the Workflow model PR to get the basic models.

Workflow viewset

---

frontend/src/components/DashboardPage.js

Added keys for repeated elements in dashboard page.

Add missing keys to mapped elements

---

backend/fms/settings.py

This will need to get merged in order to be tested remotely. The log change should be immediate.

allow localhost as ALLOWED_HOST when not on PROD. Change log to a rotating file.

---

backend/fms_core/serializers.py
backend/fms_core/viewsets/_constants.py
backend/fms_core/viewsets/sample_next_step.py

I'm not sure if this is right...

sample-next-step filters

---

frontend/src/modules/labwork/services.ts

I've been fooling around with the protocol sorting algorithm. This one is more efficient and less flaky.

Cleaner protocol sorting algorithm

---

frontend/src/components/App.js
frontend/src/components/templateFlow/TemplateFlow.js
frontend/src/modules/auth/actions.js
frontend/src/modules/shared/actions.js

Splitting up data fetches in "App.js" fetching static and dynamic data separately.

Moving static data fetch into new function

---

frontend/src/components/studySamples/CompletedSamplesTable.tsx
frontend/src/components/studySamples/StudySamples.tsx
frontend/src/models/fms_api_models.ts
frontend/src/modules/studySamples/models.ts
frontend/src/modules/studySamples/reducers.ts
frontend/src/modules/studySamples/services.ts

Display samples that are removed from a study in the study view, using the step history to identify those samples.

Display samples removed from study

---

frontend/src/components/containers/ContainersListContent.js

Replace withItem calls with withItemRenderComponent calls

Fix withItem errors

---

frontend/src/components/App.js
frontend/src/components/referenceGenomes/ReferenceGenomesListContent.tsx
frontend/src/components/referenceGenomes/ReferenceGenomesRoute.tsx
frontend/src/components/studies/WorkflowCollapsableList.tsx
frontend/src/components/taxons/TaxonsListContent.tsx
frontend/src/components/taxons/TaxonsRoute.tsx
frontend/src/components/workflows/WorkflowDefinitions.tsx
frontend/src/components/workflows/WorkflowDefinitionsRoute.tsx
frontend/src/utils/menus.js

Add a "Definitions" section to the sidebar

---

backend/fms_core/viewsets/_utils.py
backend/fms_core/viewsets/query.py
frontend/src/components/JumpBar.js

https://206.12.92.46/issues/1634

Bug #1634: Jumpbar: including an apostrophe in search query string causes 500 error

---

frontend/src/utils/templateActions.js

Added a quick check to see if the actions list is an empty array or not. Hides button if no actions are present in the component.

Hide Actions button for templates if no actions are present

---

frontend/src/components/ExportButton.js
frontend/src/components/PrefillTemplateButton.js
frontend/src/components/processes/ProcessDetailContent.js
frontend/src/modules/notification/actions.ts
frontend/src/modules/notification/actions.tsx
frontend/src/modules/notification/models.ts
frontend/src/modules/notification/reducers.ts
frontend/src/reducers.js
frontend/src/store.ts

https://206.12.92.46/issues/1614

Feature #1614: Notification management

---

frontend/src/components/ExportButton.js
frontend/src/components/PrefillTemplateButton.js
frontend/src/components/processes/ProcessDetailContent.js

I forgot to move the `key` argument into props. I blame javascript for not being type safe and not warning me of incorrect arguments >:(
https://slack-files.com/T0FDY4U73-F05B8V1CMM1-5345130ccb

Fix notification error

---

frontend/src/components/containers/ContainerFilters.tsx
frontend/src/components/containers/ContainersListContent.js
frontend/src/components/filters/descriptions.js
frontend/src/components/filters/filterGroup/FilterInput.js

https://206.12.92.46/issues/1661

Feature #1661: Add advanded filter section to containers with Comment search

---

frontend/src/components/JumpBar.js

adding async to jumpbar fetch and moving setIsFetching

Optimizing jumpbar 

---

frontend/src/components/studies/StudyDetails.tsx

https://206.12.92.46/issues/1706

Feature #1706: Reword the info in Project study page for removing a study

---

frontend/src/components/filters/FilterProps/DateRange.jsx
frontend/src/components/filters/FilterProps/InputFilter.jsx
frontend/src/components/filters/FilterProps/InputNumberFilter.jsx
frontend/src/components/filters/FilterProps/RadioFilter.jsx
frontend/src/components/filters/FilterProps/RangeFilter.jsx
frontend/src/components/filters/FilterProps/SelectFilter.jsx

https://206.12.92.46/issues/1606

Feature #1606: Close table column input filter boxes on 'Return'

---

backend/fms_core/management/commands/_update_index.py
backend/fms_core/management/commands/curation.py
backend/fms_core/migrations/0053_v4_3_0.py
backend/fms_core/models/derived_sample.py
backend/fms_core/services/derived_sample.py
backend/fms_core/tests/test_services/derived_sample_test.py

Based off the derived_from PR in order to get access to it to parse derived_samples.

Curation tool to update index

---

frontend/src/modules/cache/cache.ts
frontend/src/modules/experimentRuns/actions.js
frontend/src/modules/processes/actions.js

https://206.12.92.46/issues/1732

Feature #1732: Batch requests when sending long lists of sample ids

---

backend/fms_core/migrations/0054_v4_4_0.py
backend/fms_core/models/sample_next_step_by_study.py

- renaming index for SampleNextStepbyStudy in models, and migrations file

changing index name for samplenextstepbystudy

---

frontend/src/components/shared/WorkflowSamplesTable/ColumnSets.ts
frontend/src/components/shared/WorkflowSamplesTable/SampleTableColumns.tsx
frontend/src/components/studySamples/StudyStepSamplesTable.tsx

https://206.12.92.46/issues/1824

Feature #1824:  Display sample count column in specific protocols

---

backend/fms_core/models/individual.py

Mother cannot be male, Father cannot be female.

Additional validation for individual creation

---

backend/fms_core/filters.py
backend/fms_core/viewsets/sample_next_step.py
frontend/src/components/labwork/step/LabworkStep.tsx
frontend/src/components/samples/SampleTableColumns.tsx
frontend/src/modules/labworkSteps/services.ts

Also .... Fixed batch filtering of container barcodes.

Change ordering of containers in labwork to container name instead of barcode.

---

backend/fms_core/services/container.py
backend/fms_core/utils.py
backend/fms_core/viewsets/container.py
frontend/src/components/containers/ContainerEditContent.js

- name is already defaulted to barcode in `services/container.py`
- overwrite create in container.py viewset to use create container service
- add warnings and errors for create container services
- add errors for create container viewset

change create_container to default container name to barcode

---

frontend/src/components/PrefillTemplateColumns.tsx
frontend/src/components/labwork/step/LabworkStep.tsx

- moving refreshSelectedSamples call to tab change
- adding rowSelectHandler for selected samples table
- move rowSelection into a callback
NOTE: tried removing the formatting changes but couldn't :/

Selected Samples Fix

---

backend/fms_core/models/metric.py
backend/fms_core/services/metric.py
backend/fms_core/utils.py
backend/fms_core/viewsets/dataset.py

Also wrap the json submission in a transaction.

Changes to fix precision and scientific notation issue. 

---

frontend/src/components/WorkflowSamplesTable/WorkflowSamplesTable.tsx
frontend/src/components/labwork/step/LabworkStepOverviewPanel.tsx

This PR fixes:
- [[BUG]: Not able to enter a full text on Search option on headers in Lab Work protocols](https://206.12.92.46/issues/2072)
- [[BUG]: Fix sorting on Lab Work Samples](https://206.12.92.46/issues/2064)

Feature 2072 and 2064: Fix Labwork table loading

---

backend/fms_core/migrations/0061_v4_8_0.py
backend/fms_core/viewsets/container.py
frontend/src/components/PrefillTemplateColumns.tsx
frontend/src/components/SearchContainer.tsx
frontend/src/components/labwork/step/LabworkStep.tsx
frontend/src/components/placementVisuals/AddPlacementContainer.tsx
frontend/src/components/placementVisuals/Cell.tsx
frontend/src/components/placementVisuals/ContainerNameScroller.tsx
frontend/src/components/placementVisuals/Placement.scss
frontend/src/components/placementVisuals/Placement.tsx
frontend/src/components/placementVisuals/PlacementContainer.tsx
frontend/src/components/placementVisuals/PlacementTab.tsx
frontend/src/utils/api.js

Cut short to all that can be done here.. we'll have to come back to it...
The most important change remaining is to add clickable columns and rows for selection and an addition button to select all.

Placement support more formats

---

backend/fms_core/viewsets/sample_next_step.py
frontend/src/components/labwork/step/LabworkStep.tsx
frontend/src/components/labwork/step/LabworkStepOverview.tsx
frontend/src/components/labwork/step/LabworkStepOverviewPanel.tsx
frontend/src/models/fms_api_models.ts
frontend/src/modules/labworkSteps/actions.ts
frontend/src/modules/labworkSteps/models.ts
frontend/src/modules/labworkSteps/reducers.ts

https://206.12.92.46/issues/2097

Feature #2097:  To indicate when samples are Selected in a grouped row.

---

backend/fms_core/template_prefiller/_utils.py
backend/fms_core/template_prefiller/prefiller.py
backend/fms_core/templates.py
backend/fms_core/viewsets/_utils.py
backend/fms_core/viewsets/sample.py
backend/fms_core/viewsets/sample_next_step.py

Added section to prefilling dictionary building to process pure batch templates. Basic prefilling (without dictionary now merge entries for pure batch.

Prefill batch sheets

---

backend/fms_core/viewsets/_utils.py
backend/fms_core/viewsets/sample_next_step.py
frontend/src/components/placementVisuals/PlacementTab.tsx
frontend/src/modules/labworkSteps/services.ts
frontend/src/utils/api.js

Fix post-sample-next-step

---

frontend/src/modules/studySamples/actions.ts

Fixes the study panel displaying steps that are not part of the study workflow.

filter out steps that are not part of the study

---

backend/fms_core/viewsets/sample_next_step.py
frontend/src/components/placementVisuals/Cell.tsx
frontend/src/components/placementVisuals/Placement.tsx
frontend/src/components/placementVisuals/PlacementSamplesTable.tsx
frontend/src/models/fms_api_models.ts
frontend/src/modules/labworkSteps/actions.ts
frontend/src/modules/placement/models.ts
frontend/src/modules/placement/reducers.ts
frontend/src/utils/functions.ts

https://206.12.92.46/issues/2171
- ~[] React Error Boundary~
- ~[ ] Numbering cells during placement~
- ~[ ] Show tube name on source side for tubes without parent?~

Tweak Placement

---

backend/fms_core/filters.py

changes required to have the notification service on triton to work

added filter to retrieve latest released readsets by dataset

---

backend/fms_core/services/report.py
backend/fms_core/viewsets/report.py
frontend/src/components/reports/Reports.tsx

- New option to have Annual time window which is now the default.
- Excel exported file column width should now be better fitted to the data length.

Add Annually as the default time window

---

frontend/src/modules/placement/classes.ts

Unselect after placement
